services:
  facility-db:
    image: "postgres:16.4-alpine"
    env_file: .env
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - facility_db:/var/lib/postgresql/data

  facility:
    build: .
    env_file: .env
    depends_on:
      - facility-db
    environment:
      - PGHOST=facility-db
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - NODE_ENV=production
    volumes:
      - ./public/images/upload:/srv/client/images/upload

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - facility

volumes:
  facility_db:
  caddy_data:
  caddy_config: