INSERT INTO "glossario" ("name", "definition", "example") VALUES
    ('Peptídeo', 'Sequência curta de aminoácidos.', 'Beta-caseína.'),
    ('Transcriptômica', 'Estudo abrangente dos transcritos genéticos em uma célula ou organismo.', 'Análise da expressão gênica.'),
    ('Proteoma', 'Conjunto completo de proteínas produzidas por um organismo ou em um ambiente específico.', 'Mapeamento de interações proteína-proteína.'),
    ('Genômica', 'Estudo de todo o conjunto de genes em um organismo.', 'Anotação genômica.'),
    ('Predição de Peptídeos', 'Uso de algoritmos para prever sequências de peptídeos com base em diversos critérios.', 'Predição de peptídeos com atividade antimicrobiana.'),
    ('Busca por Nomes', 'Exploração de informações com base em nome científico, nome popular, família ou espécie.', 'Busca por "Vitamina C".'),
    ('Busca por Função Biológica', 'Pesquisa direcionada a proteínas com funções específicas, como antimicrobiana ou antioxidante.', 'Encontrar proteínas antioxidantes.'),
    ('Busca por Características Físicas', 'Investigação de peptídeos com base em propriedades físicas como peso molecular e estrutura tridimensional.', 'Pesquisa por peptídeos com peso molecular específico.'),
    ('Busca por Alimentos', 'Identificação de peptídeos e proteínas associados a alimentos específicos.', 'Buscar peptídeos em "morangos".'),
    ('Busca por Propriedades Nutricionais', 'Pesquisa com base em propriedades nutricionais, como teor de aminoácidos essenciais.', 'Encontrar proteínas ricas em aminoácidos específicos.'),
    ('Nome Científico', 'Designação única e padronizada para identificar uma espécie.', 'Byrsonima crassifolia para a Naminha.'),
    ('Nome Popular', 'Designação não científica utilizada localmente para identificar uma espécie.', '"Naminha" para Byrsonima crassifolia.'),
    ('Família', 'Agrupamento taxonômico superior que engloba diversas espécies.', 'Malpighiaceae, família da naminha.'),
    ('Espécie', 'Grupo fundamental de classificação biológica, abaixo da categoria de gênero.', 'Byrsonima crassifolia, a espécie da naminha.'),
    ('Antimicrobiana', 'Propriedade de inibir o crescimento ou eliminar microorganismos.', 'Proteínas com atividade antimicrobiana presentes em certos alimentos do cerrado e pantanal.'),
    ('Antioxidante', 'Substância que reduz ou evita danos causados pelos radicais livres.', 'Proteínas antioxidantes encontradas em frutas nativas do cerrado.'),
    ('Conservante', 'Substância que prolonga a vida útil dos alimentos inibindo a deterioração.', 'Peptídeos com propriedades conservantes em alimentos típicos do pantanal.'),
    ('Outras Funções Biológicas', 'Diversas atividades biológicas desempenhadas por proteínas e peptídeos.', 'Enzimas que contribuem para processos metabólicos específicos.'),
    ('Peso Molecular', 'Soma das massas atômicas de todos os átomos em uma molécula.', 'Peso molecular de uma proteína específica no banco de dados.'),
    ('Estrutura Tridimensional', 'Arranjo espacial dos átomos em uma molécula de proteína ou peptídeo.', 'Visualização da estrutura tridimensional de uma proteína no cerrado.'),
    ('Propriedades Físico-Químicas', 'Características relacionadas às propriedades físico-químicas de uma molécula.', 'Avaliação da hidrofobicidade e solubilidade de peptídeos presentes em alimentos do pantanal.');
